---
- name: Copy definitions.json file
  copy: src=cluster-entrypoint.sh  dest=/tmp/cluster-entrypoint.sh mode=0777


# Network containers configuration
- name: Create RabbitMQ bridge network
  docker_network:
    name: "{{ bridge_name }}"
    ipam_options:
      subnet: "{{ bridge_subnet }}"
      gateway: "{{ bridge_gateway }}"


#Start one RabbitMQ 1
- name: Start RabbitMQ1 container
  docker_container:
    name: "{{ container_1_name }}"
    hostname: "{{ container_1_name }}"
    recreate: yes
    image: "rabbitmq:3-management"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"
    networks:
      - name: "{{ bridge_name }}"
        ipv4_address: "{{ container_1_ip }}"
    env:
       RABBITMQ_ERLANG_COOKIE: "{{ ERLANG_COOKIE }}"
       RABBITMQ_DEFAULT_USER: "{{ DEFAULT_USER }}"
       RABBITMQ_DEFAULT_PASS: "{{ DEFAULT_PASS }}"
       RABBITMQ_DEFAULT_VHOST: "/"

- name: Start RabbitMQ2 container
  docker_container:
    name: "{{ container_2_name }}"
    hostname: "{{ container_2_name }}"
    recreate: yes
    image: "rabbitmq:3-management"
    networks:
      - name: "{{ bridge_name }}"
        ipv4_address: "{{ container_2_ip }}"
    env:
       RABBITMQ_ERLANG_COOKIE: "{{ ERLANG_COOKIE }}"
    volumes:
      - /tmp/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: ["sh","/usr/local/bin/cluster-entrypoint.sh"] 


- name: Start RabbitMQ3 container
  docker_container:
    name: "{{ container_3_name }}"
    hostname: "{{ container_3_name }}"
    recreate: yes
    image: "rabbitmq:3-management"
    networks:
      - name: "{{ bridge_name }}"
        ipv4_address: "{{ container_3_ip }}"
    env:
       RABBITMQ_ERLANG_COOKIE: "{{ ERLANG_COOKIE }}"
    volumes:
      - /tmp/cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
    entrypoint: ["sh","/usr/local/bin/cluster-entrypoint.sh"]
