---

# Configuration
- name: Create the conf file of each container
  template: src=rabbitmq.config.j2  dest=/tmp/rabbitmq.config-{{ item }}
  with_items:
    - rabbit1
    - rabbit2
    - rabbit3

- name: Copy definitions.json file
  copy: src=definitions.json  dest=/tmp/definitions.json

# Network
- name: Create redis bridge network
  docker_network:
    name: "rabbit_bridge"
    ipam_options:
      subnet: "{{ bridge_subnet }}"
      gateway: "{{ bridge_gateway }}"

#Start one RabbitMQ 1
- name: Start RabbitMQ1 container
  docker_container:
    name: "rabbit1"
    recreate: yes
    image: "rabbitmq:3-management"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"
    networks:
      - name: "rabbit_bridge"
        ipv4_address: "172.20.0.2"
    volumes:
      - /tmp/rabbitmq.config-rabbit1:/etc/rabbitmq/rabbitmq.config
      - /tmp/definitions.json:/etc/rabbitmq/definitions.json
    env:
       RABBITMQ_ERLANG_COOKIE: "secret string"
       RABBITMQ_NODENAME: "rabbit1"

- name: Start RabbitMQ2 container
  docker_container:
    name: "rabbit2"
    recreate: yes
    image: "rabbitmq:3-management"
    links:
      - "rabbit1:rabbit1"
    networks:
      - name: "rabbit_bridge"
        ipv4_address: "172.20.0.3"
    volumes:
      - /tmp/rabbitmq.config-rabbit2:/etc/rabbitmq/rabbitmq.config
      - /tmp/definitions.json:/etc/rabbitmq/definitions.json
    env:
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: "rabbit2"


- name: Start RabbitMQ3 container
  docker_container:
    name: "rabbit3"
    recreate: yes
    image: "rabbitmq:3-management"
    links:
      - "rabbit1:rabbit1"
      - "rabbit2:rabbit2"
    networks:
      - name: "rabbit_bridge"
        ipv4_address: "172.20.0.4"
    volumes:
      - /tmp/rabbitmq.config-rabbit3:/etc/rabbitmq/rabbitmq.config
      - /tmp/definitions.json:/etc/rabbitmq/definitions.json
    env:
      RABBITMQ_ERLANG_COOKIE: "secret string"
      RABBITMQ_NODENAME: "rabbit3"
